// Mocks generated by Mockito 5.4.6 from annotations
// in sec/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter/cupertino.dart' as _i6;
import 'package:flutter/foundation.dart' as _i7;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:sec/core/core.dart' as _i4;
import 'package:sec/core/models/github/github_model.dart' as _i9;
import 'package:sec/core/models/github_json_model.dart' as _i10;
import 'package:sec/core/models/models.dart' as _i5;
import 'package:sec/core/routing/check_org.dart' as _i20;
import 'package:sec/core/utils/result.dart' as _i15;
import 'package:sec/data/exceptions/exceptions.dart' as _i16;
import 'package:sec/data/remote_data/common/commons_api_services.dart' as _i3;
import 'package:sec/data/remote_data/update_data/data_update.dart' as _i11;
import 'package:sec/domain/use_cases/agenda_use_case.dart' as _i17;
import 'package:sec/domain/use_cases/check_token_saved_use_case.dart' as _i21;
import 'package:sec/domain/use_cases/config_use_case.dart' as _i19;
import 'package:sec/presentation/ui/screens/agenda/agenda_view_model.dart'
    as _i12;
import 'package:sec/presentation/ui/screens/config/config_viewmodel.dart'
    as _i18;
import 'package:sec/presentation/view_model_common.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommonsServices_1 extends _i1.SmartFake
    implements _i3.CommonsServices {
  _FakeCommonsServices_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDataLoader_2 extends _i1.SmartFake implements _i4.DataLoader {
  _FakeDataLoader_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfig_3 extends _i1.SmartFake implements _i5.Config {
  _FakeConfig_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueNotifier_4<T> extends _i1.SmartFake
    implements _i6.ValueNotifier<T> {
  _FakeValueNotifier_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueListenable_5<T> extends _i1.SmartFake
    implements _i7.ValueListenable<T> {
  _FakeValueListenable_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommonsServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonsServices extends _i1.Mock implements _i3.CommonsServices {
  MockCommonsServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<Map<String, dynamic>> loadData(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#loadData, [path]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i2.Response> updateData<T extends _i9.GitHubModel>(
    List<T>? dataOriginal,
    T? data,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateData, [
              dataOriginal,
              data,
              pathUrl,
              commitMessage,
            ]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#updateData, [
                  dataOriginal,
                  data,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> updateAllData(
    _i10.GithubJsonModel? data,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAllData, [data, pathUrl, commitMessage]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#updateAllData, [
                  data,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> updateDataList<T extends _i9.GitHubModel>(
    List<T>? dataList,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDataList, [
              dataList,
              pathUrl,
              commitMessage,
            ]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#updateDataList, [
                  dataList,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> removeData<T extends _i9.GitHubModel>(
    List<T>? dataOriginal,
    T? dataToRemove,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeData, [
              dataOriginal,
              dataToRemove,
              pathUrl,
              commitMessage,
            ]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#removeData, [
                  dataOriginal,
                  dataToRemove,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> removeDataList<T extends _i9.GitHubModel>(
    List<T>? dataOriginal,
    List<T>? dataToRemove,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeDataList, [
              dataOriginal,
              dataToRemove,
              pathUrl,
              commitMessage,
            ]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#removeDataList, [
                  dataOriginal,
                  dataToRemove,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);

  @override
  _i8.Future<_i2.Response> updateSingleData<T extends _i9.GitHubModel>(
    T? data,
    String? pathUrl,
    String? commitMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSingleData, [
              data,
              pathUrl,
              commitMessage,
            ]),
            returnValue: _i8.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#updateSingleData, [
                  data,
                  pathUrl,
                  commitMessage,
                ]),
              ),
            ),
          )
          as _i8.Future<_i2.Response>);
}

/// A class which mocks [DataLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataLoader extends _i1.Mock implements _i4.DataLoader {
  MockDataLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i5.Session>> loadAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllSessions, []),
            returnValue: _i8.Future<List<_i5.Session>>.value(<_i5.Session>[]),
          )
          as _i8.Future<List<_i5.Session>>);

  @override
  _i8.Future<List<_i5.Track>> loadAllTracks() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllTracks, []),
            returnValue: _i8.Future<List<_i5.Track>>.value(<_i5.Track>[]),
          )
          as _i8.Future<List<_i5.Track>>);

  @override
  _i8.Future<List<_i5.AgendaDay>> loadAllDays() =>
      (super.noSuchMethod(
            Invocation.method(#loadAllDays, []),
            returnValue: _i8.Future<List<_i5.AgendaDay>>.value(
              <_i5.AgendaDay>[],
            ),
          )
          as _i8.Future<List<_i5.AgendaDay>>);

  @override
  _i8.Future<List<_i5.Speaker>?> loadSpeakers() =>
      (super.noSuchMethod(
            Invocation.method(#loadSpeakers, []),
            returnValue: _i8.Future<List<_i5.Speaker>?>.value(),
          )
          as _i8.Future<List<_i5.Speaker>?>);

  @override
  _i8.Future<List<_i5.Sponsor>> loadSponsors() =>
      (super.noSuchMethod(
            Invocation.method(#loadSponsors, []),
            returnValue: _i8.Future<List<_i5.Sponsor>>.value(<_i5.Sponsor>[]),
          )
          as _i8.Future<List<_i5.Sponsor>>);

  @override
  _i8.Future<List<_i5.Event>> loadEvents() =>
      (super.noSuchMethod(
            Invocation.method(#loadEvents, []),
            returnValue: _i8.Future<List<_i5.Event>>.value(<_i5.Event>[]),
          )
          as _i8.Future<List<_i5.Event>>);
}

/// A class which mocks [DataUpdateInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataUpdateInfo extends _i1.Mock implements _i11.DataUpdateInfo {
  MockDataUpdateInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CommonsServices get dataCommons =>
      (super.noSuchMethod(
            Invocation.getter(#dataCommons),
            returnValue: _FakeCommonsServices_1(
              this,
              Invocation.getter(#dataCommons),
            ),
          )
          as _i3.CommonsServices);

  @override
  _i4.DataLoader get dataLoader =>
      (super.noSuchMethod(
            Invocation.getter(#dataLoader),
            returnValue: _FakeDataLoader_2(
              this,
              Invocation.getter(#dataLoader),
            ),
          )
          as _i4.DataLoader);

  @override
  _i5.Config get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeConfig_3(this, Invocation.getter(#config)),
          )
          as _i5.Config);

  @override
  _i8.Future<void> updateSpeaker(_i5.Speaker? speaker) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpeaker, [speaker]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSpeakers(List<_i5.Speaker>? speakers) =>
      (super.noSuchMethod(
            Invocation.method(#updateSpeakers, [speakers]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTrack(_i5.Track? track) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrack, [track]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTracks(List<_i5.Track>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#updateTracks, [tracks]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateAgendaDay(_i5.AgendaDay? agendaDay) =>
      (super.noSuchMethod(
            Invocation.method(#updateAgendaDay, [agendaDay]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateAgendaDays(
    List<_i5.AgendaDay>? agendaDays, {
    bool? overrideData = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateAgendaDays,
              [agendaDays],
              {#overrideData: overrideData},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSponsors(_i5.Sponsor? sponsor) =>
      (super.noSuchMethod(
            Invocation.method(#updateSponsors, [sponsor]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSponsorsList(List<_i5.Sponsor>? sponsors) =>
      (super.noSuchMethod(
            Invocation.method(#updateSponsorsList, [sponsors]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateOrganization(_i5.Config? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrganization, [config]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateEvent(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvent, [event]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateEvents(List<_i5.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#updateEvents, [events]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSession(_i5.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [session]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSessions(List<_i5.Session>? sessions) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessions, [sessions]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeSpeaker(String? speakerId, String? eventUID) =>
      (super.noSuchMethod(
            Invocation.method(#removeSpeaker, [speakerId, eventUID]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeSponsors(String? sponsorId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSponsors, [sponsorId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#removeEvent, [eventId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeAgendaDay(String? agendaDayId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAgendaDay, [agendaDayId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSession, [sessionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTrack(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrack, [trackId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> overwriteItems(List<dynamic>? itemsToKeep) =>
      (super.noSuchMethod(
            Invocation.method(#overwriteItems, [itemsToKeep]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AgendaViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendaViewModel extends _i1.Mock implements _i12.AgendaViewModel {
  MockAgendaViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ValueNotifier<List<_i5.AgendaDay>> get agendaDays =>
      (super.noSuchMethod(
            Invocation.getter(#agendaDays),
            returnValue: _FakeValueNotifier_4<List<_i5.AgendaDay>>(
              this,
              Invocation.getter(#agendaDays),
            ),
          )
          as _i6.ValueNotifier<List<_i5.AgendaDay>>);

  @override
  _i6.ValueNotifier<List<_i5.Speaker>> get speakers =>
      (super.noSuchMethod(
            Invocation.getter(#speakers),
            returnValue: _FakeValueNotifier_4<List<_i5.Speaker>>(
              this,
              Invocation.getter(#speakers),
            ),
          )
          as _i6.ValueNotifier<List<_i5.Speaker>>);

  @override
  _i6.ValueNotifier<_i13.ViewState> get viewState =>
      (super.noSuchMethod(
            Invocation.getter(#viewState),
            returnValue: _FakeValueNotifier_4<_i13.ViewState>(
              this,
              Invocation.getter(#viewState),
            ),
          )
          as _i6.ValueNotifier<_i13.ViewState>);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i15.Result<void>> saveSpeaker(
    _i5.Speaker? speaker,
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSpeaker, [speaker, eventId]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#saveSpeaker, [speaker, eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<List<_i5.Speaker>>> getSpeakersForEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpeakersForEventId, [eventId]),
            returnValue: _i8.Future<_i15.Result<List<_i5.Speaker>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.Speaker>>>(
                this,
                Invocation.method(#getSpeakersForEventId, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.Speaker>>>);

  @override
  _i8.Future<_i15.Result<void>> loadAgendaDays(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#loadAgendaDays, [eventId]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#loadAgendaDays, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<void>> removeSessionAndReloadAgenda(
    String? sessionId,
    String? eventId, {
    String? agendaDayUID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeSessionAndReloadAgenda,
              [sessionId, eventId],
              {#agendaDayUID: agendaDayUID},
            ),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(
                  #removeSessionAndReloadAgenda,
                  [sessionId, eventId],
                  {#agendaDayUID: agendaDayUID},
                ),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<void> setup([Object? argument]) =>
      (super.noSuchMethod(
            Invocation.method(#setup, [argument]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> checkToken() =>
      (super.noSuchMethod(
            Invocation.method(#checkToken, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void setErrorKey(_i16.CustomException? exception) => super.noSuchMethod(
    Invocation.method(#setErrorKey, [exception]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AgendaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgendaUseCase extends _i1.Mock implements _i17.AgendaUseCase {
  MockAgendaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i15.Result<void>> saveEvent(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#saveEvent, [event]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#saveEvent, [event]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<void>> saveSpeaker(
    _i5.Speaker? speaker,
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSpeaker, [speaker, eventId]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#saveSpeaker, [speaker, eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<_i5.AgendaDay>> getAgendaDayById(
    String? agendaDayId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAgendaDayById, [agendaDayId]),
            returnValue: _i8.Future<_i15.Result<_i5.AgendaDay>>.value(
              _i14.dummyValue<_i15.Result<_i5.AgendaDay>>(
                this,
                Invocation.method(#getAgendaDayById, [agendaDayId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<_i5.AgendaDay>>);

  @override
  _i8.Future<_i15.Result<List<_i5.AgendaDay>>> getAgendaDayByEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAgendaDayByEventId, [eventId]),
            returnValue: _i8.Future<_i15.Result<List<_i5.AgendaDay>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.AgendaDay>>>(
                this,
                Invocation.method(#getAgendaDayByEventId, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.AgendaDay>>>);

  @override
  _i8.Future<_i15.Result<List<_i5.AgendaDay>>> getAgendaDayByEventIdFiltered(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAgendaDayByEventIdFiltered, [eventId]),
            returnValue: _i8.Future<_i15.Result<List<_i5.AgendaDay>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.AgendaDay>>>(
                this,
                Invocation.method(#getAgendaDayByEventIdFiltered, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.AgendaDay>>>);

  @override
  _i8.Future<_i15.Result<List<_i5.Track>>> getTracks() =>
      (super.noSuchMethod(
            Invocation.method(#getTracks, []),
            returnValue: _i8.Future<_i15.Result<List<_i5.Track>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.Track>>>(
                this,
                Invocation.method(#getTracks, []),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.Track>>>);

  @override
  _i8.Future<_i15.Result<List<_i5.Track>>> getTracksByEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTracksByEventId, [eventId]),
            returnValue: _i8.Future<_i15.Result<List<_i5.Track>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.Track>>>(
                this,
                Invocation.method(#getTracksByEventId, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.Track>>>);

  @override
  _i8.Future<_i15.Result<void>> updateTrack(
    _i5.Track? track,
    String? agendaDayId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrack, [track, agendaDayId]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#updateTrack, [track, agendaDayId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<void>> updateAgendaDay(
    _i5.AgendaDay? agendaDay,
    String? eventUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAgendaDay, [agendaDay, eventUID]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#updateAgendaDay, [agendaDay, eventUID]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<_i5.Track>> getTrackById(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackById, [trackId]),
            returnValue: _i8.Future<_i15.Result<_i5.Track>>.value(
              _i14.dummyValue<_i15.Result<_i5.Track>>(
                this,
                Invocation.method(#getTrackById, [trackId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<_i5.Track>>);

  @override
  _i8.Future<_i15.Result<void>> addSession(
    _i5.Session? session,
    String? trackUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSession, [session, trackUID]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#addSession, [session, trackUID]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<void>> addSpeaker(
    String? eventId,
    _i5.Speaker? speaker,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSpeaker, [eventId, speaker]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#addSpeaker, [eventId, speaker]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<void>> deleteSession(
    String? sessionId, {
    String? agendaDayUID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteSession,
              [sessionId],
              {#agendaDayUID: agendaDayUID},
            ),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(
                  #deleteSession,
                  [sessionId],
                  {#agendaDayUID: agendaDayUID},
                ),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);

  @override
  _i8.Future<_i15.Result<_i5.Event>> loadEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#loadEvent, [eventId]),
            returnValue: _i8.Future<_i15.Result<_i5.Event>>.value(
              _i14.dummyValue<_i15.Result<_i5.Event>>(
                this,
                Invocation.method(#loadEvent, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<_i5.Event>>);

  @override
  _i8.Future<_i15.Result<List<_i5.Speaker>>> getSpeakersForEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpeakersForEventId, [eventId]),
            returnValue: _i8.Future<_i15.Result<List<_i5.Speaker>>>.value(
              _i14.dummyValue<_i15.Result<List<_i5.Speaker>>>(
                this,
                Invocation.method(#getSpeakersForEventId, [eventId]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<List<_i5.Speaker>>>);
}

/// A class which mocks [ConfigViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigViewModel extends _i1.Mock implements _i18.ConfigViewModel {
  MockConfigViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ValueNotifier<_i13.ViewState> get viewState =>
      (super.noSuchMethod(
            Invocation.getter(#viewState),
            returnValue: _FakeValueNotifier_4<_i13.ViewState>(
              this,
              Invocation.getter(#viewState),
            ),
          )
          as _i6.ValueNotifier<_i13.ViewState>);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  set errorMessage(String? value) => super.noSuchMethod(
    Invocation.setter(#errorMessage, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> updateConfig(_i5.Config? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [config]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setup([Object? argument]) =>
      (super.noSuchMethod(
            Invocation.method(#setup, [argument]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> checkToken() =>
      (super.noSuchMethod(
            Invocation.method(#checkToken, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void setErrorKey(_i16.CustomException? exception) => super.noSuchMethod(
    Invocation.method(#setErrorKey, [exception]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConfigUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigUseCase extends _i1.Mock implements _i19.ConfigUseCase {
  MockConfigUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i15.Result<void>> updateConfig(_i5.Config? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [config]),
            returnValue: _i8.Future<_i15.Result<void>>.value(
              _i14.dummyValue<_i15.Result<void>>(
                this,
                Invocation.method(#updateConfig, [config]),
              ),
            ),
          )
          as _i8.Future<_i15.Result<void>>);
}

/// A class which mocks [CheckOrg].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOrg extends _i1.Mock implements _i20.CheckOrg {
  MockCheckOrg() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ValueListenable<bool> get hasErrorListenable =>
      (super.noSuchMethod(
            Invocation.getter(#hasErrorListenable),
            returnValue: _FakeValueListenable_5<bool>(
              this,
              Invocation.getter(#hasErrorListenable),
            ),
          )
          as _i7.ValueListenable<bool>);

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  void setError(bool? v) => super.noSuchMethod(
    Invocation.method(#setError, [v]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CheckTokenSavedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckTokenSavedUseCase extends _i1.Mock
    implements _i21.CheckTokenSavedUseCase {
  MockCheckTokenSavedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> checkToken() =>
      (super.noSuchMethod(
            Invocation.method(#checkToken, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
