// Mocks generated by Mockito 5.4.6 from annotations
// in sec/test/presentation/event_detail/event_detail_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sec/core/models/models.dart' as _i5;
import 'package:sec/core/utils/result.dart' as _i4;
import 'package:sec/domain/use_cases/check_token_saved_use_case.dart' as _i7;
import 'package:sec/domain/use_cases/event_use_case.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EventUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventUseCase extends _i1.Mock implements _i2.EventUseCase {
  MockEventUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Event>>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Event>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Event>>>(
                this,
                Invocation.method(#getEvents, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Event>>>);

  @override
  _i3.Future<_i4.Result<_i5.Event?>> getEventById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Event?>>.value(
              _i6.dummyValue<_i4.Result<_i5.Event?>>(
                this,
                Invocation.method(#getEventById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Event?>>);

  @override
  _i3.Future<_i4.Result<void>> saveEvent(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#saveEvent, [event]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveEvent, [event]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeEvent(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#removeEvent, [event]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeEvent, [event]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> prepareAgendaDays(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#prepareAgendaDays, [event]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#prepareAgendaDays, [event]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeTrack(String? trackUID) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrack, [trackUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeTrack, [trackUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateConfig(_i5.Config? config) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [config]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateConfig, [config]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [CheckTokenSavedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckTokenSavedUseCase extends _i1.Mock
    implements _i7.CheckTokenSavedUseCase {
  MockCheckTokenSavedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> checkToken() =>
      (super.noSuchMethod(
            Invocation.method(#checkToken, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [Config].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfig extends _i1.Mock implements _i5.Config {
  MockConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get configName =>
      (super.noSuchMethod(
            Invocation.getter(#configName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#configName),
            ),
          )
          as String);

  @override
  String get primaryColorOrganization =>
      (super.noSuchMethod(
            Invocation.getter(#primaryColorOrganization),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#primaryColorOrganization),
            ),
          )
          as String);

  @override
  String get secondaryColorOrganization =>
      (super.noSuchMethod(
            Invocation.getter(#secondaryColorOrganization),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#secondaryColorOrganization),
            ),
          )
          as String);

  @override
  String get githubUser =>
      (super.noSuchMethod(
            Invocation.getter(#githubUser),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#githubUser),
            ),
          )
          as String);

  @override
  String get projectName =>
      (super.noSuchMethod(
            Invocation.getter(#projectName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#projectName),
            ),
          )
          as String);

  @override
  String get branch =>
      (super.noSuchMethod(
            Invocation.getter(#branch),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#branch),
            ),
          )
          as String);

  @override
  set eventForcedToViewUID(String? value) => super.noSuchMethod(
    Invocation.setter(#eventForcedToViewUID, value),
    returnValueForMissingStub: null,
  );

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  String get pathUrl =>
      (super.noSuchMethod(
            Invocation.getter(#pathUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#pathUrl),
            ),
          )
          as String);

  @override
  String get updateMessage =>
      (super.noSuchMethod(
            Invocation.getter(#updateMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#updateMessage),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
