// Mocks generated by Mockito 5.4.6 from annotations
// in sec/test/domain/use_cases/speaker_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sec/core/models/models.dart' as _i5;
import 'package:sec/core/utils/result.dart' as _i4;
import 'package:sec/domain/repositories/sec_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SecRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecRepository extends _i1.Mock implements _i2.SecRepository {
  MockSecRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Event>>> loadEvents() =>
      (super.noSuchMethod(
            Invocation.method(#loadEvents, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Event>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Event>>>(
                this,
                Invocation.method(#loadEvents, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Event>>>);

  @override
  _i3.Future<_i4.Result<_i5.Event>> loadEventById(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#loadEventById, [eventId]),
            returnValue: _i3.Future<_i4.Result<_i5.Event>>.value(
              _i6.dummyValue<_i4.Result<_i5.Event>>(
                this,
                Invocation.method(#loadEventById, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Event>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Speaker>>> loadESpeakers() =>
      (super.noSuchMethod(
            Invocation.method(#loadESpeakers, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Speaker>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Speaker>>>(
                this,
                Invocation.method(#loadESpeakers, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Speaker>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Sponsor>>> loadSponsors() =>
      (super.noSuchMethod(
            Invocation.method(#loadSponsors, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Sponsor>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Sponsor>>>(
                this,
                Invocation.method(#loadSponsors, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Sponsor>>>);

  @override
  _i3.Future<_i4.Result<_i5.AgendaDay>> loadAgendaDayById(
    String? agendaDayId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAgendaDayById, [agendaDayId]),
            returnValue: _i3.Future<_i4.Result<_i5.AgendaDay>>.value(
              _i6.dummyValue<_i4.Result<_i5.AgendaDay>>(
                this,
                Invocation.method(#loadAgendaDayById, [agendaDayId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AgendaDay>>);

  @override
  _i3.Future<_i4.Result<List<_i5.AgendaDay>>> loadAgendaDayByEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAgendaDayByEventId, [eventId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.AgendaDay>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.AgendaDay>>>(
                this,
                Invocation.method(#loadAgendaDayByEventId, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.AgendaDay>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.AgendaDay>>> loadAgendaDayByEventIdFiltered(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadAgendaDayByEventIdFiltered, [eventId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.AgendaDay>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.AgendaDay>>>(
                this,
                Invocation.method(#loadAgendaDayByEventIdFiltered, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.AgendaDay>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Track>>> loadTracksByEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadTracksByEventId, [eventId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Track>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Track>>>(
                this,
                Invocation.method(#loadTracksByEventId, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Track>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Track>>> loadTracks() =>
      (super.noSuchMethod(
            Invocation.method(#loadTracks, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Track>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Track>>>(
                this,
                Invocation.method(#loadTracks, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Track>>>);

  @override
  _i3.Future<_i4.Result<_i5.Track>> loadTrackById(String? trackId) =>
      (super.noSuchMethod(
            Invocation.method(#loadTrackById, [trackId]),
            returnValue: _i3.Future<_i4.Result<_i5.Track>>.value(
              _i6.dummyValue<_i4.Result<_i5.Track>>(
                this,
                Invocation.method(#loadTrackById, [trackId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Track>>);

  @override
  _i3.Future<_i4.Result<void>> saveEvent(_i5.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#saveEvent, [event]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveEvent, [event]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveConfig(_i5.Config? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveConfig, [config]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveTracks(List<_i5.Track>? tracks) =>
      (super.noSuchMethod(
            Invocation.method(#saveTracks, [tracks]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveTracks, [tracks]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveTrack(
    _i5.Track? track,
    String? agendaDayId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveTrack, [track, agendaDayId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveTrack, [track, agendaDayId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveAgendaDays(
    List<_i5.AgendaDay>? agendaDays,
    String? eventUID, {
    bool? overrideAgendaDays = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveAgendaDays,
              [agendaDays, eventUID],
              {#overrideAgendaDays: overrideAgendaDays},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #saveAgendaDays,
                  [agendaDays, eventUID],
                  {#overrideAgendaDays: overrideAgendaDays},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveSpeaker(
    _i5.Speaker? speaker,
    String? parentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSpeaker, [speaker, parentId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveSpeaker, [speaker, parentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeSpeaker(
    String? speakerId,
    String? eventUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeSpeaker, [speakerId, eventUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeSpeaker, [speakerId, eventUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveAgendaDay(
    _i5.AgendaDay? agendaDay,
    String? eventUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAgendaDay, [agendaDay, eventUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveAgendaDay, [agendaDay, eventUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeAgendaDay(
    String? agendaDayId,
    String? eventUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeAgendaDay, [agendaDayId, eventUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeAgendaDay, [agendaDayId, eventUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> addSession(
    _i5.Session? session,
    String? trackUID,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSession, [session, trackUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#addSession, [session, trackUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> addSpeaker(
    String? eventId,
    _i5.Speaker? speaker,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSpeaker, [eventId, speaker]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#addSpeaker, [eventId, speaker]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteSession(
    String? sessionId, {
    String? agendaDayUID,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteSession,
              [sessionId],
              {#agendaDayUID: agendaDayUID},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #deleteSession,
                  [sessionId],
                  {#agendaDayUID: agendaDayUID},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> saveSponsor(
    _i5.Sponsor? sponsor,
    String? parentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveSponsor, [sponsor, parentId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveSponsor, [sponsor, parentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeSponsor(String? sponsorId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSponsor, [sponsorId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeSponsor, [sponsorId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeEvent(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#removeEvent, [eventId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeEvent, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeTrack(String? trackUID) =>
      (super.noSuchMethod(
            Invocation.method(#removeTrack, [trackUID]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeTrack, [trackUID]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Speaker>>> getSpeakersForEventId(
    String? eventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSpeakersForEventId, [eventId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Speaker>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Speaker>>>(
                this,
                Invocation.method(#getSpeakersForEventId, [eventId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Speaker>>>);
}
